name: Deploy workflow
run-name: Deploying application
on:
    pull_request:
        types:
            - closed

jobs:
    deploy:
        name: Upload to Amazon S3
        runs-on: ubuntu-latest
        # These permissions are needed to interact with GitHub's OIDC Token endpoint.
        permissions:
          id-token: write
          contents: read
        steps:
        - name: Checkout
          uses: actions/checkout@v2
    
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
    
        - name: Copy files to the production website with the AWS CLI
          run: |
            aws s3 sync . s3://hackathonfrontend

            